# fly.toml app configuration file generated for billys-terraria-server on 2024-02-19T15:40:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'billys-terraria-server'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'opt'
  destination = '/opt/'

[[services]]
  protocol = 'tcp'
  internal_port = 7777
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
    port = 7777

[[vm]]
  size = 'performance-2x'
